# Setup
title:            Sheila Mbadi
tagline:          'Applied Machine Learning Enthusiast'
description:      'A software engineer and an applied machine learning enthusiast commited to building high quality software'
url:              https://sheilambadi.github.io/
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Sheila Mbadi'
  url:            https://twitter.com/sheilambadi

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
